name: AutoDev

on:
  pull_request:
    types: [labeled, unlabeled, closed]
  push:
    branches-ignore:
      - dev

jobs:
  autodev:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: github.actor != 'dependabot[bot]' && (github.event_name == 'push' || github.event.label.name == 'dev' || github.event.action == 'closed')
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          fetch-tags: false
      - uses: Staffbase/autodev-action@feat/conflict-blame-comments
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: dev
          label: dev
          comments: "true"
          labels: "true"
          success_label: "dev-ok"
          failure_label: "dev-failed"
